name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/back_ground_image.png
    - assets/images/rectangle_161.jpeg
    - assets/images/rectangle_165.jpeg
    - assets/images/rectangle_16.jpeg
    - assets/images/rectangle_166.jpeg
    - assets/images/rectangle_167.jpeg
    - assets/images/rectangle_171.jpeg
    - assets/images/rectangle_17.jpeg
    - assets/images/rectangle_162.jpeg
    - assets/images/rectangle_168.jpeg
    - assets/images/rectangle_163.jpeg
    - assets/images/back_ground_image.png
    - assets/vectors/vector_56_x2.svg
    - assets/vectors/icon_17_x2.svg
    - assets/vectors/vector_193_x2.svg
    - assets/vectors/vector_19_x2.svg
    - assets/vectors/vector_113_x2.svg
    - assets/vectors/vector_100_x2.svg
    - assets/vectors/vector_102_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_2_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_31_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/rectangle_72_x2.svg
    - assets/vectors/icon_16_x2.svg
    - assets/vectors/rectangle_71_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_22_x2.svg
    - assets/images/time_management.png
    - assets/images/group_39577.png
    - assets/images/image.png
    - assets/images/mobile_credit_card_and_money.png
    - assets/images/people_1.png
    - assets/images/result_icon_1.png
    - assets/images/img_icons_81.png
    - assets/images/bus_21.png
    - assets/images/back_ground_image.png
    - assets/images/bubble.png
    - assets/images/roommate_1.png
    - assets/images/attandance_icon_1.png
    - assets/images/image_34.png
    - assets/images/film_clapper_popcorn_and_movie_tickets.png
    - assets/images/workplace_with_stacks_of_books.png
    - assets/images/trail_map.png
    - assets/vectors/vector_2_x2.svg
    - assets/vectors/vector_30_x2.svg
    - assets/vectors/vector_134_x2.svg
    - assets/vectors/notification_x2.svg
    - assets/vectors/logosgoogle_gmail_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/vector_146_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_1_x2.svg
    - assets/vectors/group_713_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_61_x2.svg
    - assets/images/download_7.jpeg
    - assets/images/download_2.jpeg
    - assets/images/images_14.jpeg
    - assets/images/download_1.jpeg
    - assets/images/images_12.jpeg
    - assets/images/images_9.jpeg
    - assets/images/images_15.jpeg
    - assets/images/images_8.jpeg
    - assets/images/images_10.jpeg
    - assets/images/download_4.jpeg
    - assets/images/download_3.jpeg
    - assets/images/download_5.jpeg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_7_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_30_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/vector_1813_x2.svg
    - assets/vectors/vector_1811_x2.svg
    - assets/vectors/icon_41_x2.svg
    - assets/vectors/vector_182_x2.svg
    - assets/vectors/vector_1812_x2.svg
    - assets/vectors/vector_18_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/vector_1814_x2.svg
    - assets/vectors/icon_66_x2.svg
    - assets/images/back_ground_image.png
    - assets/images/back_ground_image.png
    - assets/images/back_ground_image.png
    - assets/images/back_ground_image.png
    - assets/vectors/icon_64_x2.svg
    - assets/images/rectangle_168.jpeg
    - assets/images/rectangle_163.jpeg
    - assets/images/rectangle_161.jpeg
    - assets/images/back_ground_image.png
    - assets/images/rectangle_167.jpeg
    - assets/images/image_42.png
    - assets/images/image_41.png
    - assets/images/image_44.png
    - assets/images/rectangle_181.jpeg
    - assets/images/rectangle_183.jpeg
    - assets/images/rectangle_164.jpeg
    - assets/images/rectangle_182.jpeg
    - assets/vectors/vector_66_x2.svg
    - assets/vectors/icon_14_x2.svg
    - assets/vectors/vector_172_x2.svg
    - assets/vectors/vector_182_x2.svg
    - assets/vectors/vector_49_x2.svg
    - assets/vectors/vector_6_x2.svg
    - assets/vectors/vector_153_x2.svg
    - assets/vectors/vector_28_x2.svg
    - assets/vectors/vector_15_x2.svg
    - assets/vectors/vector_11_x2.svg
    - assets/vectors/vector_98_x2.svg
    - assets/vectors/vector_64_x2.svg
    - assets/vectors/vector_188_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/download_animations_8_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_67_x2.svg
    - assets/vectors/icon_24_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_20_x2.svg
    - assets/images/n_2.jpeg
    - assets/vectors/ellipse_12_x2.svg
    - assets/vectors/ellipse_14_x2.svg
    - assets/vectors/container_3_x2.svg
    - assets/vectors/icon_19_x2.svg
    - assets/vectors/ellipse_13_x2.svg
    - assets/vectors/vector_84_x2.svg
    - assets/vectors/ellipse_11_x2.svg
    - assets/vectors/ellipse_17_x2.svg
    - assets/vectors/ellipse_1_x2.svg
    - assets/vectors/ellipse_16_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_55_x2.svg
    - assets/images/back_ground_image.png
    - assets/images/back_ground_image.png
    - assets/vectors/icon_56_x2.svg
    - assets/images/image.jpeg
    - assets/images/dsc_045851.jpeg
    - assets/images/dsc_021581.jpeg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_4_x2.svg
    - assets/images/fixed_aspect_ratio_cover_elements_on_top_3.jpeg
    - assets/images/back_ground_image.png
    - assets/images/fixed_aspect_ratio_cover_elements_on_top_1.png
    - assets/images/fixed_aspect_ratio_cover_elements_on_top_2.png
    - assets/images/fixed_aspect_ratio_cover_elements_on_top.jpeg
    - assets/vectors/icon_9_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_65_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_37_x2.svg
    - assets/images/image_32.png
    - assets/images/image_33.png
    - assets/images/image_31.png
    - assets/vectors/eisearch_x2.svg
    - assets/vectors/icon_53_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_54_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_5_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/vector_18_x2.svg
    - assets/vectors/icon_40_x2.svg
    - assets/images/a_3_pu_campus_map_2023_r_1_c_2_clatest_page_00011.jpeg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_18_x2.svg
    - assets/images/n_2.jpeg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_43_x2.svg
    - assets/images/back_ground_image.png
    - assets/images/back_ground_image.png
    - assets/vectors/icon_48_x2.svg
    - assets/vectors/vector_87_x2.svg
    - assets/vectors/vector_128_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/star_5_x2.svg
    - assets/vectors/star_4_x2.svg
    - assets/vectors/star_2_x2.svg
    - assets/vectors/icon_35_x2.svg
    - assets/vectors/star_1_x2.svg
    - assets/vectors/star_3_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_33_x2.svg
    - assets/vectors/time_tabe_x2.svg
    - assets/images/back_ground_image.png
    - assets/images/back_ground_image.png
    - assets/vectors/icon_11_x2.svg
    - assets/images/back_ground_image.png
    - assets/images/image_35.png
    - assets/images/image_39.png
    - assets/images/image_38.png
    - assets/images/image_37.png
    - assets/vectors/icon_25_x2.svg
    - assets/images/back_ground_image.png
    - assets/images/image_35.png
    - assets/images/back_ground_image.png
    - assets/vectors/icon_12_x2.svg
    - assets/images/back_ground_image.png
    - assets/vectors/icon_52_x2.svg
    - lib/pages/attandance_1.dart